### ISSUE TITLE
Code failed to build on Mac M1

### ISSUE THREAD

**Issue by testn** [spotbugs/spotbugs#2280]
It seems to refer to the older version of Eclipse which does not support Mac M1

**Comment by gtoison** [comment]
This should be fixed according to #2507

**Comment by hazendaz** [comment]
closing as addressed.  Further we expect after this next release to start raising our jdk requirements so we can then bring eclipse up much further.  it is true its stuck in time but we are aware of the issues and working on it.  As noted this was fixed already on master with changes I did earlier.  The PR noted will show multi platform usage.  If still an issue after this next release, please reopen but as noted we will fast track moving up to newer releases.

**Comment by Spatrik95** [comment]
Hello! I still have this kind of problem. I'm on an Apple Mac M2 with Sonoma 14.0.  
On a `./gradlew clean bulld` I get the following message:
```
Execution failed for task ':eclipsePlugin:compileJava'.
> Could not resolve all files for configuration ':eclipsePlugin:compileClasspath'.
   > Could not find org.eclipse.platform:org.eclipse.swt.cocoa.macosx.aarch64:3.113.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/eclipse/platform/org.eclipse.swt.cocoa.macosx.aarch64/3.113.0/org.eclipse.swt.cocoa.macosx.aarch64-3.113.0.pom
     Required by:
         project :eclipsePlugin > org.eclipse.platform:org.eclipse.swt:3.113.0
```

Currently the only way, is a workaround: I exclude these modules from the build process:  
```
./gradlew clean build -x :eclipsePlugin:compileJava -x :eclipsePlugin-junit:compileTestJava -x :eclipsePlugin-test:compileJava -x :eclipsePlugin-test:checkstyleMain
```

**Comment by hazendaz** [comment]
Are you building from latest master?  The version you listed is older than our current master and latest eclipse supports the arm module at least per eclipse github.  The 3.113 version is from 2019.  I think if you rebase it may work.  Clearly 2019 eclipse would not support that arch type 😉

Now even if that solves it for you, we are going to slightly move back to eclipse 4.25 release so you may want to check existing recent pull request I raised a few days ago to check it as well.

Thanks for work around in any case as it may help other contributors.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Spatrik95** [comment]
@hazendaz I built from the head of the master branch, so it's up to date. I get the following dependency tree: 
[dependencies.zip](https://github.com/spotbugs/spotbugs/files/12837061/dependencies.zip)

I tried to `./gradlew clean --refresh-dependencies` but I still have the same result.

If I change the https://github.com/spotbugs/spotbugs/blob/master/buildSrc/src/main/kotlin/eclipse-convention.gradle.kts#L10 version to newer, like `4.29.0`, it's compile. So maybe we should simply update this version.

**Comment by hazendaz** [comment]
Thanks I see your pull request.  I simply had missed that one.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JuditKnoll** [comment]
Since https://github.com/spotbugs/spotbugs/pull/2611 got merged, closing this issue. Thank you for checking and the PR, @Spatrik95 !

**Comment by radeva** [comment]
@JuditKnoll @Spatrik95 @hazendaz In case you want free minutes on M1, you can try [FlyCI](https://www.flyci.net/)'s M1 and M2 runners. They are on average 2x faster and 2x cheaper than GitHub's **AND** we have a **free tier for OSS projects** (see below).

# Install Instructions

1. Install [FlyCI app](https://github.com/apps/flyci-prod) and 
2. Easily replace one line of code and start using FlyCI runners:

```diff
jobs:
 ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m1
   steps:
   - name: 👀 Checkout repo
     uses: actions/checkout@v4
```
# 500 mins/month Free for Public Repos

Since your repo is public, FlyCI offers **500 mins/month of free M1 runner usage** with the `flyci-macos-large-latest-m1` runner for public projects. 

Don't hesitate to contact us in case the free tier doesn't suit your needs or you experience any issues with the runners. Our team is here to support you!

Best Regards,
Veselina Radeva
Product Manager at [FlyCI](https://flyci.net/)

**Comment by hazendaz** [comment]
@radeva Thank you!  Is m2 not free for OSS, just the m1?

**Comment by hazendaz** [comment]
I did add m1, worked out well for us.  Thanks.

**Comment by radeva** [comment]
> @radeva Thank you! Is m2 not free for OSS, just the m1?

Yep, only M1 is free. Feel free to try M2 though, we won't charge you if it's in the next week.
