### ISSUE TITLE
spotbugs API is not exported by the Eclipse plugin anymore

### ISSUE THREAD

**Issue by sewe** [spotbugs/spotbugs#478]
I just noticed a pretty severe problem:

The [com.github.spotbugs.plugin.eclipse bundle](https://github.com/spotbugs/eclipse/blob/gh-pages/plugins/com.github.spotbugs.plugin.eclipse_3.1.0.r201710241414-11c9895.jar) from out SpotBugs 3.1.0 stable update site has the following in its `MANIFEST.MF`:

    Require-Bundle: …,spotbugs;resolution:=optional;visibility:=reexport,
     spotbugs-annotations;resolution:=optional;visibility:=reexport
    Bundle-ClassPath: spotbugs-plugin.jar,lib/spotbugs.jar,lib/spotbugs-annotations.jar,…

But the `lib/spotbugs.jar` thus referenced is *not* an OSGi bundle anymore:

    Manifest-Version: 1.0
    Automatic-Module-Name: com.github.spotbugs.spotbugs
    Bundle-Version: 3.1.0
    Class-Path: asm-analysis-6.0.jar asm-commons-6.0.jar asm-xml-6.0.jar a
     sm-util-6.0.jar asm-tree-6.0.jar asm-6.0.jar bcel-6.1.jar jcip-annota
     tions-1.0.jar dom4j-1.6.1.jar jaxen-1.1.6.jar commons-lang-2.6.jar jF
     ormatString-3.0.0.jar spotbugs-annotations.jar xml-apis-1.0.b2.jar js
     r305-3.0.2.jar
    Main-Class: edu.umd.cs.findbugs.LaunchAppropriateUI

This means that the `Require-Bundle: spotbugs;resolution:=optional;visibility:=reexport` is not satisfied and hence packages like `edu.umd.cs.findbugs` are no longer exported. This breaks *every* Eclipse plugin that extends the `edu.umd.cs.findbugs.plugin.eclipse.findbugsQuickFixes` extension point and does not explicitly import `edu.umd.cs.findbugs` and friends, as it is impossible to extend `edu.umd.cs.findbugs.plugin.eclipse.quickfix.BugResolution` without loading classes like `edu.umd.cs.findbugs.BugInstance`. Triggering such a quickfix results in a `ClassNotFoundException` at runtime.

**Comment by sewe** [comment]
> This means that the Require-Bundle: spotbugs;resolution:=optional;visibility:=reexport is not satisfied

This raises the question: Why on earth is this an optional `Require-Bundle`? We ship the `spotbugs` bundle (or non-bundle, in this case) in our own `lib` folder and put it on the `Bundle-Classpath`.

If this were a mandatory `Require-Bundle` this problem would have become obvious as soon as you install the SpotBugs Eclipse plug-in – and it fails to resolve.

**Comment by sewe** [comment]
FWIW, this bug did not occur with previous *stable* Eclipse plugin. But as the 3.1.0 apparently killed the entire commit history of https://github.com/spotbugs/eclipse, I am not sure what RC that was.

**Comment by iloveeclipse** [comment]
Andreas, I'm not sure which concrete big do you have. Findbugs core was never a bundle, so never spotbugs jar. The require attributes in eclipse plugin manifest are for PDE tooling only - so that one can debug eclipse plugin from eclipse and if the spotbugs core project is found in the workspace, it is identified by PDE as a "bundle". In the "real" word eclipse plugin consumes all core packages from jars located inside the eclipse plugin itself, so it can see all of them and of course export all of them.

If you also see some specific regression now with the spotbugs plugin, it can be either because it has a different bundle id, or it simply does not export some of the packages previously exported - so all what we need them to check which are missimg and add them to the manifest template.

**Comment by sewe** [comment]
> Findbugs core was never a bundle, so never spotbugs jar.

Yes, it’s true that the `spotbugs.jar` [downloadable from Maven Central](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.github.spotbugs%22%20AND%20a%3A%22spotbugs%22) is not an OSGi bundle – although the manifest for some reason contains a `Bundle-Version` (but no `Bundle-ManifestVersion` or `Bundle-SymbolicName`).

> Andreas, I'm not sure which concrete bug do you have.

Here’s a description: I use PDE to build an Eclipse plug-in with a `BugResolution` quickfix. My `.target` file references `com.github.spotbugs.plugin.eclipse.feature.group` from https://spotbugs.github.io/eclipse/. My plug-in contains the following in its manifest:

    Require-Bundle: com.github.spotbugs.plugin.eclipse;bundle-version="[3.1.0,3.2.0)", …

As of yesterday (the 3.1.0 release), my Eclipse plug-in suddenly fails to build (in both PDE and Maven/Tycho) with the same error message:

    Access restriction: The type 'BugInstance' is not API (restriction on required library '/Users/sewe/Documents/oomph/com.codetrails/ws/.metadata/.plugins/org.eclipse.pde.core/.bundle_pool/plugins/com.github.spotbugs.plugin.eclipse_3.1.0.r201710241414-11c9895/lib/spotbugs.jar')

This is no surprise as the `com.github.spotbugs.plugin.eclipse` `3.1.0.r201710241414-11c9895` bundle does not `Export-Package` `edu.umd.cs.findbugs`. And the re-export of the `Require-Bundle` `spotbugs;resolution:=optional;visibility:=reexport` seems to be a moot now, as apparently there is no OSGi bundle with `Bundle-SymbolicName` `spotbugs`. (Why is it even there?)

Does this make sense?

**Comment by sewe** [comment]
> As of yesterday (the 3.1.0 release), my Eclipse plug-in suddenly fails to build (in both PDE and Maven/Tycho) [...]

What is worse, a version of my Eclipse plug-in previously built successfully against the last stable version on https://spotbugs.github.io/eclipse/ now fails **at runtime** when triggering the quickfix:

    org.eclipse.core.runtime.CoreException: Plug-in "com.codetrails.connect.findbugs.rcp" was unable to instantiate class "com.codetrails.internal.connect.findbugs.rcp.quickfix.IgnoreCallOrderingQuickfix".
	    at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:194)
    …
    Caused by: java.lang.NoClassDefFoundError: edu/umd/cs/findbugs/filter/Matcher
    …
    Caused by: java.lang.ClassNotFoundException: edu.umd.cs.findbugs.filter.Matcher cannot be found by com.codetrails.connect.findbugs.rcp_2.7.4.v20171023-2201-b818

This is clearly a regression.

**Comment by iloveeclipse** [comment]
@sewe : the missing packages were there since juni, see #216. I've pushed a possible fix.

**Comment by sewe** [comment]
> the missing packages were there since juni, see #216.

@iloveeclipse I take this as “if you had regularly built against https://spotbugs.github.io/eclipse-latest/ rather than stable than you would have detected this issue sooner.” Good point.

> I've pushed a possible fix.

You mean 147f829c02940440bf8cba151bc3209e09ce476d? That looks good to me. Let’s hope it will make it into 3.1.1 soon.

**Comment by iloveeclipse** [comment]
:-)
Can you please check if *all* packages you were missing are now visible?

**Comment by sewe** [comment]
> Can you please check if all packages you were missing are now visible?

You missed at least `edu.umd.cs.findbugs.bytecode`. More comments in your change.

**Comment by iloveeclipse** [comment]
Just realized this was fixed & released already -> closing.

**Comment by iloveeclipse** [comment]
And now realized that the fix only went into 3.1.0 branch 👎
Reopening.
