### ISSUE TITLE
Gradle-daemon: Trying to add already registered factory fills stdout

### ISSUE THREAD

**Issue by dellgreen** [spotbugs/spotbugs#819]
When using gradle daemon i constantly get a lot of output for subsequent runs after the first run. Is daemon caching clashing with spotbugs logging? Seems to happens when adding spotbugs plugins
I have findsecbugs plugin and one i have written myself

Trying to add already registered factory: IwSlf4jLoggers, Plugin:uk.co.ideaworks.spotbugs.spotbugs-plugin
Trying to add already registered factory: PredictableRandomDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: ServletEndpointDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: CookieReadDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: CookieFlagsDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: PathTraversalDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: CommandInjectionDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: WeakFilenameUtilsMethodDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: WeakTrustManagerDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: JaxWsEndpointDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: JaxRsEndpointDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: TapestryEndpointDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: WicketEndpointDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: WeakMessageDigestDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: WeakTLSDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: CustomMessageDigestDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: FileUploadFilenameDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: ReDosDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: XxeDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: TransformerFactoryDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: XmlStreamReaderDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: XPathInjectionDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: Struts1EndpointDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: Struts2EndpointDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: SpringMvcEndpointDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: SpringCsrfProtectionDisabledDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: SpringCsrfUnrestrictedRequestMappingDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: CustomInjectionDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: SqlInjectionDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: AndroidSqlInjectionDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: BadHexadecimalConversionDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: HazelcastSymmetricEncryptionDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: NullCipherDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: UnencryptedSocketDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: UnencryptedServerSocketDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: DesUsageDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: TDesUsageDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: RsaNoPaddingDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: ConstantPasswordDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: GoogleApiKeyDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: HardcodePasswordInMapDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: IntuitiveHardcodePasswordDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: HardcodedPasswordEqualsDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: HashUnsafeEqualsDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: KotlinHardcodedPasswordEqualsDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: StrutsValidatorFormDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: XSSRequestWrapperDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: InsufficientKeySizeBlowfishDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: InsufficientKeySizeRsaDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: UnvalidatedRedirectDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: XssJspDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: XssServletDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: JspIncludeDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: JspSpringEvalDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: JstlOutDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: XslTransformJspDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: StdXmlTransformDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: XmlDecoderDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: StaticIvDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: CipherWithNoIntegrityDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: EsapiEncryptorDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: ScriptInjectionDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: OgnlInjectionDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: SpelViewDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: HttpResponseSplittingDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: CrlfLogInjectionDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: ExternalConfigurationControlDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: ExternalFileAccessDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: BroadcastDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: WorldWritableDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: GeolocationDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: WebViewJavascriptEnabledDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: WebViewJavascriptInterfaceDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: ObjectDeserializationDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: UnsafeJacksonDeserializationDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: DeserializationGadgetDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: TrustBoundaryViolationAttributeDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: TrustBoundaryViolationValueDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: PlayUnvalidatedRedirectDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: SslDisablerDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: ScalaSensitiveDataExposureDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: SSRFDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: XssMvcApiDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: XssTwirlDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: VelocityDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: FreemarkerDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: LdapInjectionDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: AnonymousLdapDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: LdapEntryPoisoningDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: PermissiveCORSDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: PersistentCookieDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: UrlRewritingDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: InsecureSmtpSslDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: AwsQueryInjectionDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: BeanInjectionDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: FileDisclosureDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: FormatStringManipulationDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: HttpParameterPollutionDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: SmtpHeaderInjectionDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: SpringUnvalidatedRedirectDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: PotentialValueDetector, Plugin:com.h3xstream.findsecbugs
Trying to add already registered factory: ErrorMessageExposureDetector, Plugin:com.h3xstream.findsecbugs

------------------------------------------------------------
Gradle 5.0
------------------------------------------------------------

Build time:   2018-11-26 11:48:43 UTC
Revision:     7fc6e5abf2fc5fe0824aec8a0f5462664dbcd987

Kotlin DSL:   1.0.4
Kotlin:       1.3.10
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_191 (Oracle Corporation 25.191-b12)
OS:           Linux 4.15.0-39-generic amd64

Spotbugs Version: 3.1.8/3.1.9
Spotbugs Gradle Plugin Version: 1.6.5

**Comment by KengoTODA** [comment]
#720 could be related this issue, I guess.

**Comment by d1ss0nanz** [comment]
Issue still present with spotbugs 3.1.10.

**Comment by wreulicke** [comment]
I tried to investigate this issue.
I found singleton [here](https://github.com/spotbugs/spotbugs/blob/release-3.1/spotbugs/src/main/java/edu/umd/cs/findbugs/DetectorFactoryCollection.java#L129).
 and [here](https://github.com/spotbugs/spotbugs/blob/release-3.1/spotbugs/src/main/java/edu/umd/cs/findbugs/Plugin.java#L60).

I seem that there is a threading issue.

**Comment by wreulicke** [comment]
@dellgreen 
Do you have multiple sub projects in gradle project?

**Comment by dellgreen** [comment]
no single project

**Comment by davidburstromspotify** [comment]
This also happens if you're using Spotbugs Gradle plugin 3.1.5+ which uses the Gradle Worker API. Previously each task would run in its own JVM, thus avoiding the repeated addition.

**Comment by kstarsinic** [comment]
Is this a bug in Gradle or in the plugin, then, or something else?

**Comment by kstarsinic** [comment]
The bug does not seem to be manifesting with gradle 5.1 + spotbugs plugin 1.6.8.

**Comment by dellgreen** [comment]
Still happens using gradle 5.1 and spotbugs gradle plugin 1.6.9

**Comment by d1ss0nanz** [comment]
Still happens using gradle 5.1 and spotbugs gradle plugin 1.6.10

**Comment by KengoTODA** [comment]
Can someone reproduce this issue with spotbugs-gradle-plugin 1.6.4? I guess that this was caused by https://github.com/spotbugs/spotbugs-gradle-plugin/pull/58 in 1.6.5 but I cannot reproduce this issue in my local.

When we confirm that 1.6.4 cannot reproduce but 1.6.5+ can reproduce, I'll revert https://github.com/spotbugs/spotbugs-gradle-plugin/pull/58 and release 1.6.11.

**Comment by dellgreen** [comment]
I have tried  going back to 1.6.4, however it causes spotbugs to silently fail to produce any xml report file. 1.6.5 produces an xml report.

**Comment by kstarsinic** [comment]
I can confirm that 1.6.4 does not reproduce the bug. I am not seeing the issue that @dellgreen had; the plugin generated an xml report for me. For reference, here are the spotbugs-related parts of my build.gradle:
```groovy
plugins {
  id 'java'
  id 'application'
  id 'com.github.spotbugs' version '1.6.4'
}

dependencies {
  compileOnly     group: 'com.github.spotbugs',        name: 'spotbugs',         version: '3.1.10'
  spotbugsPlugins group: 'com.h3xstream.findsecbugs',  name: 'findsecbugs-plugin', version: '1.8.0'
  spotbugsPlugins group: 'com.mebigfatguy.fb-contrib', name: 'fb-contrib',         version: '7.4.3.sb'
}

spotbugs {
  effort        = 'max'
  reportLevel   = 'medium'
  excludeFilter = file('config/spotbugsExcludeFilter.xml')
  showProgress  = true
}

tasks.withType(com.github.spotbugs.SpotBugsTask) {
  reports {
    ignoreFailures  = true
    xml.enabled     = true
    html.enabled    = false
  }
}
```

**Comment by KengoTODA** [comment]
Thank you! I will try to revert that change in master branch.

**Comment by KengoTODA** [comment]
I prepared a fix at https://github.com/spotbugs/spotbugs-gradle-plugin/tree/revert-58

If you can reproduce this issue in your local, please help me to verify my fix:

1. build and install the fixed gradle plugin into your maven local repository
2. bump up the version of gradle plugin in your `build.gradle` to `1.6.10-SNAPSHOT`
3. add `mavenLocal()` to use SNAPSHOT version in your maven local repository. See [this blog post](https://shekhargulati.com/2015/09/10/gradle-tip-using-gradle-plugin-from-local-maven-repository/) as reference.
4. then run the build as usual, to confirm that problem has been fixed or not.

Here is necessary commands to install gradle plugin into your maven local repository:

```sh
git clone git@github.com:spotbugs/spotbugs-gradle-plugin.git
cd spotbugs-gradle-plugin
git checkout revert-58
./gradlew install
```

Thanks in advance!

**Comment by d1ss0nanz** [comment]
revert-58 fixes the issue for me.

**Comment by safetytrick** [comment]
revert-58 works for me as well

**Comment by KengoTODA** [comment]
Thanks for all! Then I will merge that PR, and release a patch version in that gradle plugin project.

**Comment by kstarsinic** [comment]
I spoke too soon. I still get many "Trying to add already registered factory" messages, but it doesn't appear to happen on every run.

**Comment by KengoTODA** [comment]
Hello users, please have a try with newly released [gradle plugin version 1.6.10](https://github.com/spotbugs/spotbugs-gradle-plugin/releases/tag/1.6.10). It includes the fix that I requested you to test in your project. I hope it fixes your problem.

**Comment by pgelinas** [comment]
I've done multiple run with the new version and can confirm that this issue is fixed.

**Comment by dellgreen** [comment]
yes this have fixed it for me also

**Comment by davidburstromspotify** [comment]
@KengoTODA The flipside to the revert is that without using the worker API, executing our SpotBugs task take about 400% longer time. We (Spotify) were very happy to see the adoption of the worker API and will not be able to bump to 1.6.10 as it's such a regression in build times.

**Comment by KengoTODA** [comment]
Thanks for your feedback! Then I will close this issue.

@davidburstromspotify Thanks for your feedback! We have related discussion at https://github.com/spotbugs/spotbugs-gradle-plugin/pull/100, please come and propose changes to fix our problem :)
